[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Judson <nyarly@gmail.com>"]
publish = false

[dependencies]
num = "0.1.35"
num-bigint = "0.1.35"
rustc-serialize = "0.3"
lazy_static = "0.2.1"
rust-crypto = "^0.2"
rand = "0.3"
